### ISSUE TITLE
Expected release date

### ISSUE THREAD

**Issue by robingenz** [VapiAI/ios#19]
Is there any information on when this library will be released? We would like to integrate it into our iOS app.

**Comment by nikhilro** [comment]
hey @robingenz, this should be good to use right now. what blocker are you running into?

**Comment by robingenz** [comment]
I need to set a version at `from` when I include the package. I don't have much experience with SPM (only with cocoapods), but doesn't a git tag need to be created for this?

```swift
.package(url: "https://github.com/VapiAI/ios", from: "<VERSION>"),
```

There is also no GitHub release in this repository.

**Comment by nikhilro** [comment]
does this help: https://github.com/VapiAI/ios?tab=readme-ov-file#installation? 

if not, throw claude or o1 on it?

**Comment by robingenz** [comment]
I have already looked at the installation guide. As I said, I have to set a version when I include the package. This is the error message from XCode:

![grafik](https://github.com/user-attachments/assets/184e57bf-b5e6-472b-af1f-41c9baa814b3)

**Comment by robingenz** [comment]
@nikhilro My client would really like to use your SDK. Are there any updates here? The installation guide seems to be outdated (see Xcode error message).

**Comment by robingenz** [comment]
It seems as if the documentation has been updated.

**Comment by nikhilro** [comment]
perfect, sorry i forgot to update here
